### ISSUE TITLE
Pest test run fails - "Unable to locate a class or view for component [filament-support::grid]"

### ISSUE THREAD

**Issue by camya** [ralphjsmit/laravel-filament-components#13]
Hi Ralph

I tried to run the included Pest tests. Unfortunaltey each test fails with the same error message: `Unable to locate a class or view for component [filament-support::grid]`

The Exception looks like this:

```
• Tests\Forms\SidebarTest > it can create a sidebar
   Illuminate\View\ViewException

  Unable to locate a class or view for component [filament-support::grid]. (View: /vendor/ralphjsmit/laravel-filament-components/vendor/filament/forms/resources/views/component-container.blade.php) (View: /vendor/ralphjsmit/laravel-filament-components/vendor/filament/forms/resources/views/component-container.blade.php)

  at vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:323
    319▕         if (Str::startsWith($component, 'mail::')) {
    320▕             return $component;
    321▕         }
    322▕
  ➜ 323▕         throw new InvalidArgumentException(
    324▕             "Unable to locate a class or view for component [{$component}]."
    325▕         );
    326▕     }
    327▕

      +8 vendor frames
  9   [internal]:0
      Illuminate\View\Compilers\ComponentTagCompiler::Illuminate\View\Compilers\{closure}()
```

**Comment by ralphjsmit** [comment]
Hey Andreas, thanks, just fixed 👍 Not released, but don't think you need a release?

**Comment by camya** [comment]
Hey Ralph, thank you for the quick fix. No release needed. 

The bug report was a bit self-serving because you are the only one who has a Pest test for a Filament plugin :D Very cool.

I tried to use your Pest test implementation for my Filament plugin and stumbled across the error message. ;)

I will add you for sure to the "inspired by" section in my plugin readme. 

Thank you Ralph.

**Comment by ralphjsmit** [comment]
Awesome, no problem. Always nice to hear that it was useful! 

Is that the Filament Title With Slug plugin? Looks good!

**Comment by camya** [comment]
> Is that the Filament Title With Slug plugin? Looks good!

Yes, it is. :) Thank you. I released the latest version of the "Title With Slug" plugin with the Pest Tests today. Btw, you're mentioned in the changelog and documentation. :)

Maybe your Pest Test implentation is worth a entry in the **Filament Tricks** section?

This would be useful for other Filament developers for sure.

**Comment by ralphjsmit** [comment]
Ok, cool! Thanks, it wasn't necessary to mention me, but it's appreciated 😊

Adding it as a trick is a nice, I'll write it down to do it. 👍
